version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install boto3
      - pip install gitpython
      #      or install your dependencies from requirements.txt
      #      - pip i#nstall -r requirements.txt -t lib
      - echo "Finish installing dependencies"
  build:
    commands:
      - echo "begin build step & loading deployment script from s3"
      - aws s3 cp s3://codebuild-metadata/deploy-lambda.py deploy-lambda.py
      - echo "run deployment script"
      - python deploy-lambda.py
      - echo "finish deployment"
